// This file was automatically generated by dev/schemas.ts
import AutomationProcess from './AutomationProcess.json';
import AutomationStepJump from './AutomationStepJump.json';
import AutomationTask from './AutomationTask.json';
import AutomationTemplate from './AutomationTemplate.json';
import EventbusMessage from './EventbusMessage.json';

export const schemas = {
  AutomationProcess,
  AutomationStepJump,
  AutomationTask,
  AutomationTemplate,
  EventbusMessage,
};
